export class OrderList {
  id:number;
  orignum:string;
  regdate:Date;
  user_id:number;
  status:number;
  whouse_id:number;
  cost:number;
  amount:number;
  isdeleted:number;
  transportcompany:number;
  delivery_type:number;    
  delivery_date:Date;
  whouse_name:string;
  status_name:string;
  status_color:string;
  commentary:string;
  delivery_typename:string;
  delivery_address:string;
  detailDescr:string;
  sber_1c_status:number;
}